import { BasicColors, MainColors } from '../../common/index'
import { ms } from '../../helper/index'
import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  completedView: {
    width: ms(330, 0.5),
    height: 68,
    backgroundColor: MainColors.accentLighter,
    borderRadius: 12,
    alignSelf: 'center',
    alignItems: 'center',
    paddingRight: ms(20, 0.5),
    paddingLeft: ms(17, 0.5),
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    shadowColor: MainColors.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    marginBottom: 15,
  },
  circleNormalView: {
    width: ms(20, 0.5),
    height: ms(20, 0.5),
    borderRadius: ms(10, 0.5),
    backgroundColor: MainColors.circle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trashSvg: {
    position: 'absolute',
    top: 10,
    left: ms(8.9, 0.5),
  },
  programItemView: {
    width: ms(330, 0.5),
    height: 68,
    backgroundColor: BasicColors.white,
    zIndex: -500,
    borderRadius: 12,
    alignSelf: 'center',
    alignItems: 'center',
    shadowColor: MainColors.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    marginBottom: 15,
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
    paddingRight: ms(20, 0.5),
  },
  normalItemView: {
    width: ms(330, 0.5),
    height: 68,
    backgroundColor: BasicColors.white,
    borderRadius: 12,
    alignSelf: 'center',
    alignItems: 'center',
    shadowColor: MainColors.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    marginBottom: 15,
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
    paddingRight: ms(20, 0.5),
    paddingLeft: ms(17, 0.5),
  },
  finishedCircle: {
    width: ms(20, 0.5),
    height: ms(20, 0.5),
    borderRadius: ms(10, 0.5),
    backgroundColor: BasicColors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markedExercisesView: {
    backgroundColor: MainColors.markedExercises,
    width: ms(330, 0.5),
    height: 68,
    borderRadius: 12,
    alignSelf: 'center',
    alignItems: 'center',
    marginBottom: 15,
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
    paddingRight: ms(20, 0.5),
    paddingLeft: ms(17, 0.5),
  },
  rightView: {
    // alignItems: 'flex-end',

  },
  leftView: {
    flexDirection: 'row-reverse' ,
  },
  leftTitleText: {
    marginRight : ms(8, 0.5),
  },
  bookmarkSvg: {
    position: 'absolute',
    top: 0,
    left: ms(48.2, 0.5),
  },
  absoluteView: {
    position: 'absolute',
  },
})
