import { BasicColors, MainColors, windowW } from '../../common/index'
import { ms } from '../../helper/sizing'
import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  containerView: {
    flex: 1,
    backgroundColor: BasicColors.white,
  },
  stopwatchContainer: {
    position: 'absolute',
    top: 132,
    width: windowW,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
  },
  commonHeader: {
    backgroundColor: MainColors.primary,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  customStopwatch: {},
  lapPress: {
    width: 30,
    height: 30,
    borderRadius: 18,
    position: 'absolute',
    top: 277,
    left: (windowW - 24) / 2,
    zIndex: 1000,
  },
  higherTopView: {
    width: '100%',
    height: 339,
    backgroundColor: BasicColors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topView: {
    width: '100%',
    height: 339,
    backgroundColor: MainColors.primary,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lapsFlatList: {
    marginTop: 20,
    alignSelf: 'center',
    width: ms(320, 0.5),
    backgroundColor: BasicColors.white,
  },
  loopsContainer: {
    backgroundColor: BasicColors.white,
    width: '100%',
    minHeight: 355,
    paddingBottom: 80,
    alignSelf: 'center',
  },
  lineView: {
    width: ms(320, 0.5),
    height: 0.6,
    backgroundColor: MainColors.linePrimary,
    alignSelf: 'center',
    marginVertical: 11,
  },
  leftLapView: {},
  lapView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: ms(320, 0.5),
    alignItems: 'flex-end',
  },
  squareView: {
    width: 15,
    height: 15,
    backgroundColor: BasicColors.white,
  },
  obstacleLapView: {
    zIndex: 500,
    position: 'absolute',
    width: 30,
    height: 30,
  },
  circlePlayView: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: MainColors.primaryLighter,
    justifyContent: 'center',
    alignItems: 'center',
  },
  threeOptionsView: {
    alignItems: 'center',
    width: ms(250, 0.5),
    height: 50,
    backgroundColor: BasicColors.white,
    paddingHorizontal: ms(22, 0.5),
    flexDirection: 'row',
    justifyContent: 'space-between',
    shadowColor: MainColors.shadow,
    alignSelf: 'center',
    borderRadius: 26,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: 'absolute',
    bottom: 25,
  },
  obstacleView: {
    width: ms(53.5, 0.5),
    height: 25,
    backgroundColor: MainColors.primary,
    top: 0,
    position: 'absolute',
    left: ms(80, 0.5),
    zIndex: 5,
  },
})
